[package]
name = "catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
coyote = { workspace = true }
coyote_html = { workspace = true }
config = { path = "../config" }
futures = { workspace = true }
pages = { path = "../pages" }
